line-length = 120
indent-width = 4
target-version = "py312"

exclude = [".venv", ]

[lint]
select = ["E", "F", "I", "B"]
fixable = ["ALL", ]

[format]
quote-style = "double"
line-ending = "lf"
indent-style = "space"
skip-magic-trailing-comma = false
