$ANSIBLE_VAULT;1.1;AES256
39656334313135333033306638666336636166333464623132343132316136306163363730396330
3737313362663833383363326332643735356561646235350a343239653433666231306633393766
61336438316132663235306635393865303462393439383365633730323031643730323566626366
3936386664336332660a366437646266373563323737623033363130643365366166343834343065
65386437373266353234613061636266363334386534653464343739653630623630333461313132
61336266653936656638363835316361323966633961313364353230663232383961653066623332
34343565383934333239313835333135303136356164666639646165636365646638383431356132
64313533383739383862
